#!/bin/bash

# Generate a random string to use as the secret key
FLASK_SECRET_KEY=$(openssl rand -base64 32)

# Set the FLASK_SECRET_KEY environment variable
export FLASK_SECRET_KEY=$FLASK_SECRET_KEY

# Start the Flask app
flask run --host=0.0.0.0 -p 8199
